apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: automotive-ot-lab
spec:
  nodes:
    - general:
        hostname: eng-ws
        description: Engineering Workstation (with SCEPTRE CLI)
      hardware:
        drives:
          - image: ubuntu.qc2
        memory: 8192
        vcpus: 4
        os_type: linux
      network:
        interfaces:
          - name: mgmt
            address: 192.168.100.10
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: plc-1
        description: Simulated PLC controlling robot arm
      hardware:
        drives:
          - image: protonuke.qc2
        memory: 2048
        vcpus: 2
        os_type: linux
      network:
        interfaces:
          - name: eth0
            address: 192.168.100.20
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: rtu-1
        description: Simulated RTU collecting sensor data
      hardware:
        drives:
          - image: protonuke.qc2
        memory: 2048
        vcpus: 2
        os_type: linux
      network:
        interfaces:
          - name: eth0
            address: 192.168.100.30
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: hmi-1
        description: HMI interface for monitoring and control
      hardware:
        drives:
          - image: ubuntu.qc2
        memory: 4096
        vcpus: 2
        os_type: linux
      network:
        interfaces:
          - name: eth0
            address: 192.168.100.40
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: field-sim
        description: Simulated field device (sensor or actuator)
      hardware:
        drives:
          - image: protonuke.qc2
        memory: 2048
        vcpus: 1
        os_type: linux
      network:
        interfaces:
          - name: eth0
            address: 192.168.100.50
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: router-ot
        description: Local OT router (VyOS)
      hardware:
        drives:
          - image: vyos.qc2
        os_type: linux
      network:
        interfaces:
          - name: ot-net
            address: 192.168.100.1
            mask: 24
            type: ethernet
            proto: static
            vlan: OT
      type: Router
