apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: PowerGridLab
spec:
  nodes:
    - general:
        hostname: eng-ws
        description: Engineering Workstation (with SCEPTRE)
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.0.10
            mask: 24
            gateway: 10.0.0.1
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: hmi
        description: Human Machine Interface
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.0.11
            mask: 24
            gateway: 10.0.0.1
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: plc-1
        description: PLC 1
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.0.20
            mask: 24
            gateway: 10.0.0.1
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: plc-2
        description: PLC 2
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.0.21
            mask: 24
            gateway: 10.0.0.1
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: rtu
        description: Remote Terminal Unit
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.0.30
            mask: 24
            gateway: 10.0.0.1
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine

    - general:
        hostname: historian
        description: Historian Server
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.1.10
            mask: 24
            gateway: 10.0.1.1
            proto: static
            type: ethernet
            vlan: DMZ
      type: VirtualMachine

    - general:
        hostname: dmz-fw
        description: DMZ Firewall/Gateway
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            address: 10.0.1.1
            mask: 24
            gateway: 10.0.1.254
            proto: static
            type: ethernet
            vlan: DMZ
          - name: eth1
            address: 10.0.0.1
            mask: 24
            proto: static
            type: ethernet
            vlan: OT
      type: VirtualMachine
