apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: PowerGrid
spec:
  nodes:
    - general:
        hostname: plc-1
        description: Primary PLC handling actuator control
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.10
            mask: 24

    - general:
        hostname: plc-2
        description: Secondary PLC with redundancy
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.11
            mask: 24

    - general:
        hostname: hmi-1
        description: HMI station 1
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.20
            mask: 24

    - general:
        hostname: hmi-2
        description: HMI station 2
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.21
            mask: 24

    - general:
        hostname: eng-ws-1
        description: Engineering Workstation 1
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.30
            mask: 24

    - general:
        hostname: eng-ws-2
        description: Engineering Workstation 2
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.31
            mask: 24

    - general:
        hostname: historian
        description: Data Historian server
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.40
            mask: 24

    - general:
        hostname: dmz-fw
        description: OT Firewall / DMZ
      hardware:
        os_type: linux
        memory: 1024
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            proto: static
            address: 10.0.0.50
            mask: 24
