apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: automotive_factory_lab
spec:
  nodes:
    # HMI Terminals
    - general:
        hostname: hmi-1
        description: HMI Terminal 1
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.10
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: hmi-2
        description: HMI Terminal 2
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.11
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: hmi-3
        description: HMI Terminal 3
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.12
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: hmi-4
        description: HMI Terminal 4
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.13
            mask: 24
            gateway: 192.168.100.1

    # PLCs
    - general:
        hostname: plc-1
        description: PLC Unit 1
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.20
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: plc-2
        description: PLC Unit 2
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.21
            mask: 24
            gateway: 192.168.100.1

    # Engineering Workstations
    - general:
        hostname: eng-ws-1
        description: Engineering Workstation 1
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.30
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: eng-ws-2
        description: Engineering Workstation 2
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.31
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: eng-ws-3
        description: Engineering Workstation 3
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.32
            mask: 24
            gateway: 192.168.100.1

    - general:
        hostname: eng-ws-4
        description: Engineering Workstation 4
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.33
            mask: 24
            gateway: 192.168.100.1

    # IDS/IPS
    - general:
        hostname: ids
        description: IDS/IPS System
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.40
            mask: 24
            gateway: 192.168.100.1

    # Historian
    - general:
        hostname: historian
        description: Data Historian Server
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.50
            mask: 24
            gateway: 192.168.100.1

    # DMZ Server
    - general:
        hostname: dmz-fw
        description: DMZ Firewall
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: OT
            address: 192.168.100.100
            mask: 24
            gateway: 192.168.100.1
          - name: eth1
            type: ethernet
            proto: static
            vlan: DMZ
            address: 10.10.10.1
            mask: 24

    - general:
        hostname: dmz-server
        description: DMZ Service Host
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            vlan: DMZ
            address: 10.10.10.2
            mask: 24
