apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: dallas-instruments-ot
spec:
  nodes:
    - type: VirtualMachine
      general:
        hostname: hmi-1
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.11
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: hmi-2
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.12
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: hmi-3
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.13
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: hmi-4
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.14
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: plc-1
      hardware:
        os_type: linux
        vcpus: 2
        memory: 2048
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.21
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: plc-2
      hardware:
        os_type: linux
        vcpus: 2
        memory: 2048
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.22
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: eng-ws-1
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.31
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: eng-ws-2
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.32
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: eng-ws-3
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.33
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: eng-ws-4
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.34
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: ids-ips
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.40
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: historian
      hardware:
        os_type: linux
        vcpus: 2
        memory: 4096
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.50
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: dmz-fw
      hardware:
        os_type: linux
        vcpus: 2
        memory: 2048
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.100
            mask: 24
            proto: static

    - type: VirtualMachine
      general:
        hostname: dmz-server
      hardware:
        os_type: linux
        vcpus: 2
        memory: 2048
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            vlan: OT
            address: 10.0.0.101
            mask: 24
            proto: static
