apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: automotive-factory-ot
spec:
  nodes:
  # HMI Terminals
  - general:
      hostname: hmi-1
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.11
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: hmi-2
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.12
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: hmi-3
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.13
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: hmi-4
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.14
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  # PLCs
  - general:
      hostname: plc-1
    hardware:
      vcpus: 2
      memory: 2048
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.21
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: plc-2
    hardware:
      vcpus: 2
      memory: 2048
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.22
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  # Engineering Workstations
  - general:
      hostname: eng-ws-1
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.31
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: eng-ws-2
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.32
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: eng-ws-3
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.33
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  - general:
      hostname: eng-ws-4
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.34
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  # IDS/IPS (with Splunk if added later)
  - general:
      hostname: ids
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.40
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine

  # Historian Server
  - general:
      hostname: historian
    hardware:
      vcpus: 2
      memory: 4096
      os_type: linux
      drives:
      - image: ubuntu.qc2
    network:
      interfaces:
      - name: ot-net
        address: 192.168.100.50
        mask: 24
        gateway: 192.168.100.1
        proto: static
        type: ethernet
    type: VirtualMachine
