apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: linux-desktops-test
spec:
  nodes:
    - type: VirtualMachine
      general:
        hostname: ubuntu-desktop-1
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu-desktop.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            address: 192.168.110.10
            gateway: 192.168.110.1
            mask: 24
            vlan: DESKTOPS

    - type: VirtualMachine
      general:
        hostname: ubuntu-desktop-2
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu-desktop.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            address: 192.168.110.11
            gateway: 192.168.110.1
            mask: 24
            vlan: DESKTOPS
