apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: kali-bennu-demo
spec:
  nodes:
    - type: VirtualMachine
      general:
        hostname: kali-attacker
      hardware:
        os_type: linux
        memory: 4096
        vcpus: 2
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            address: 192.168.60.10
            gateway: 192.168.60.1
            mask: 24
            vlan: DEMO
        startup:
          - command: "ping -c 4 192.168.60.20 > /root/ping-results.txt"
          - command: "nmap -sS -p 502 192.168.60.20 -oN /root/nmap-scan.txt"

    - type: VirtualMachine
      general:
        hostname: bennu-rtu
      hardware:
        os_type: linux
        memory: 2048
        vcpus: 1
        drives:
          - image: bennu.qc2
      network:
        interfaces:
          - name: eth0
            type: ethernet
            proto: static
            address: 192.168.60.20
            gateway: 192.168.60.1
            mask: 24
            vlan: DEMO
        startup:
          - command: "/opt/bennu/bin/bennu -c /opt/bennu/configs/test-config.toml > /var/log/bennu.log 2>&1"
