apiVersion: phenix.sandia.gov/v1
kind: Scenario
metadata:
  name: minimal-scenario
  created: ""
  updated: ""
spec:
  apps:
    - name: sceptre
      metadata:
        provider:
          - hostname: rtu-1
            type: test                         # tells Bennu to use bennu-test-ep-server
        field_devices:
          - hostname: rtu-1
            type: fd-server
            provider: rtu-1                    # uses itself as provider
            infrastructure: power-transmission
            cycle_time: 1.0
            modbus:
              - name: Bus1_Voltage
                type: bus
              - name: Breaker12_Status
                type: breaker
