apiVersion: phenix.sandia.gov/v1
kind: Scenario
metadata:
  name: minimal-scenario
  annotations:
    topology: minimal-modbus-demo
  created: ""
  updated: ""
spec:
  apps:
    sceptre:
      metadata:
        field_devices:
          - hostname: rtu-1
            type: fd-server
            infrastructure: power-transmission
            cycle_time: 1.0
            modbus:
              - name: Bus1_Voltage
                type: bus
              - name: Breaker12_Status
                type: breaker
