apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: minimal-modbus-demo
spec:
  nodes:
    - type: VirtualMachine
      general:
        hostname: rtu-1
        description: Simulated Bennu RTU with Modbus
      hardware:
        os_type: linux
        vcpus: 1
        memory: 1024
        drives:
          - image: bennu.qc2
      network:
        interfaces:
          - name: eth0
            vlan: OT
            address: 192.168.100.10
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static

    - type: VirtualMachine
      general:
        hostname: attacker-1
        description: Linux attacker VM with nmap
      hardware:
        os_type: linux
        vcpus: 1
        memory: 1024
        drives:
          - image: ubuntu.qc2
      network:
        interfaces:
          - name: eth0
            vlan: OT
            address: 192.168.100.20
            mask: 24
            gateway: 192.168.100.1
            type: ethernet
            proto: static
